spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: create
  show-sql: true


spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-227-68-43.compute-1.amazonaws.com/d369h396junsm6
  username: fnwgwsquytetex
  password: ec5b19966ad72c2bde735205b12c7bf3dfed1e35dc5036015f1ed99e30a48c7c
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: phh-sns-application-2022.secret_key
  # 30days
  token.expired-time-ms: 2592000000